# fly.toml app configuration file generated for new-lo-bot on 2023-08-26T15:21:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "new-lo-bot"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
